global/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
# from exam import views as auth_view
admin.site.site_header = 'Dashboard'                    # default: "Django Administration"
admin.site.index_title = 'Admin Panel'                 # default: "Site administration"
admin.site.site_title = 'Admin Panel' # default: "Django site admin"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # password reset
    path('reset_password', auth_views.PasswordResetView.as_view(template_name='reset.html'), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name='sent.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='updatePW.html'), name="password_reset_confirm" ),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="complete.html"), name= "password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name='home'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('team/', views.team_list, name='team_list'),
    path('team/<slug:slug>/', views.team_detail, name='team_detail'),
    path('blogs/', views.blog, name='blog'),
    path('blogs/<str:pk>/', views.blog_detail, name='blog_detail'),

    path('services/', views.service_list, name='service_list'),
     path('services/<slug:slug>/', views.service_detail, name='service_detail'),
    path('contact/', views.contact, name='contact'),
]

home/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

class Team(models.Model):
    name = models.CharField(max_length=150)
    position = models.CharField(max_length=150)
    slug = models.SlugField(unique=True, blank=True)
    
    facebook = models.URLField(blank=True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    twitter = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    
    description = RichTextField()
    image = models.ImageField(upload_to='team/', blank=True, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['name']
        verbose_name = "Team Member"
        verbose_name_plural = "Team Members"

    def __str__(self):
        return f"{self.name} - {self.position}"

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.name)
            slug = base_slug
            counter = 1
            # Ensure unique slug
            while Team.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)



class Category(models.Model):
    category = models.CharField(max_length = 156)
    def __str__(self):
        return self.category
    

class Tags(models.Model):
    tags = models.CharField(max_length = 156)
    def __str__(self):
        return self.tags   




class Blog(models.Model):
    status  = models.BooleanField(default=True)
    
    h1  = models.CharField(max_length = 156)
    slug =models.CharField(max_length = 1256,blank=True, null=True)
    page_name = models.CharField(max_length = 1256,blank=True, null=True)
    keyword = models.CharField(max_length = 156)
    description = models.CharField(max_length = 900)
    title = models.CharField(max_length = 156)
    breadcrumb = models.CharField(max_length = 156)
    canonical = models.CharField(max_length = 900, default="https://compassionatecareadvisors.com/blogs/")
    og_type =models.CharField(max_length = 156)
    og_card = models.CharField(max_length = 156)
    og_site = models.CharField(max_length = 156)
    og_title=models.CharField(max_length = 100,blank=True, null=True)
    meta_title=models.CharField(max_length = 100,blank=True, null=True)
    og_description=models.CharField(max_length = 250,blank=True, null=True)
    meta_description=models.CharField(max_length = 250,blank=True, null=True)
    image  = models.ImageField(upload_to="SEO")
    
    banner_image  = models.ImageField(upload_to="banner", blank=True, null=True)
    category = models.ManyToManyField(Category)
    tag  = models.ManyToManyField(Tags)
    updated  = models.DateField(auto_now=True)
    

    
    
    published  = models.DateField()
    content = RichTextUploadingField()
    active = True
    edits = RichTextUploadingField( blank=True, null=True)
    schema = models.TextField(blank=True, null=True)
    
    
    def __str__(self):
        return self.h1 






class Service(models.Model):
    # Basic info
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    short_description = models.TextField(blank=True, null=True)
    content = RichTextUploadingField()
    
    # Banner image
    banner_image = models.ImageField(upload_to="services/banner/", blank=True, null=True)
    
    # SEO fields
    meta_title = models.CharField(max_length=100, blank=True, null=True)
    meta_description = models.CharField(max_length=250, blank=True, null=True)
    meta_keywords = models.CharField(max_length=250, blank=True, null=True)
    canonical = models.URLField(max_length=500, blank=True, null=True)
    
    # Open Graph / Social sharing
    og_title = models.CharField(max_length=200, blank=True, null=True)
    og_description = models.CharField(max_length=250, blank=True, null=True)
    og_type = models.CharField(max_length=50, default="website")
    og_url = models.URLField(max_length=500, blank=True, null=True)
    og_image = models.ImageField(upload_to="services/og/", blank=True, null=True)
    
    # Status & timestamps
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    



class ContactMessage(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=20, blank=True, null=True)
    company = models.CharField(max_length=200, blank=True, null=True)
    message = models.TextField()
    agree_terms = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.email}"

home/forms.py
from django import forms
from .models import ContactMessage

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'phone', 'company', 'message', 'agree_terms']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'placeholder': 'Phone', 'class': 'form-control'}),
            'company': forms.TextInput(attrs={'placeholder': 'Company Name', 'class': 'form-control'}),
            'message': forms.Textarea(attrs={'placeholder': 'Message', 'class': 'form-control', 'rows': 5}),
        }

home/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404
from .models import Blog, Team
from .models import Service
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import ContactForm


# Create your views here.
def home(request):
    teams = Team.objects.all()
    context = {
        'teams': teams,
    }
    return render(request, 'index.html', context)


def about(request):
    teams = Team.objects.all()
    data = Blog.objects.all().order_by('-id')
    context = {
        'teams': teams,
        'data': data,
    }
    return render(request, 'about.html', context)




def team_list(request):
    teams = Team.objects.all()
    return render(request, 'team/team_list.html', {'teams': teams})

def team_detail(request, slug):
    team = get_object_or_404(Team, slug=slug)
    return render(request, 'team/team_detail.html', {'team': team})



def blog(request):
    data = Blog.objects.all().order_by('-id')
    context = {
        'data':data,
    }
    return render(request, 'blog/blogs.html', context)

def blog_detail(request, pk):
    data = Blog.objects.get(slug=pk)
    data2 = Blog.objects.all().order_by('-id')[:7]
    context = {
        'data':data,
        'data2':data2,
    }
    return render(request, 'blog/blog_detail.html', context)




def service_list(request):
    data = Service.objects.all().order_by('-id')
    context = {
        'data':data,
    }
    return render(request, 'services/services.html', context)



def service_detail(request, slug):
    service = get_object_or_404(Service, slug=slug)
    data2 = Service.objects.all().order_by('-id')[:7]
    
    # If you want to show recent/other services
    recent_services = Service.objects.filter(status=True).exclude(id=service.id).order_by('-created_at')[:5]
    
    context = {
        'service': service,
        'recent_services': recent_services,
        'data2': data2,
    }
    return render(request, 'services/service_detail.html', context)





def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your message has been sent successfully!")
            return redirect('home:contact')  # redirect to the same page
    else:
        form = ContactForm()
    
    return render(request, 'contact.html', {'form': form})

home/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block seo %}
<title>{{ data.meta_title }}</title>
<meta name="description" content="{{ data.meta_description }}">
<link rel="canonical" href="{{ data.canonical }}">
<meta property="og:type" content="{{ data.og_type }}">
<meta property="og:title" content="{{ data.og_title }}">
<meta property="og:description" content="{{ data.og_description }}">
<meta property="og:image" content="{{ data.image.url }}">
{% endblock seo %}

{% block body %}
<main>

    <!-- breadcrumb area start -->
    <section class="bd-breadcrumb-area p-relative fix">
        <div class="bd-breadcrumb-bg" data-background="{{ data.banner_image.url }}"></div>
        <div class="bd-breadcrumb-wrapper p-relative">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-10">
                        <div class="bd-breadcrumb d-flex align-items-center justify-content-center">
                            <div class="bd-breadcrumb-content text-center">
                                <h1 class="bd-breadcrumb-title">{{ data.breadcrumb }}</h1>
                                <div class="bd-breadcrumb-list">
                                    <span><a href="{% url 'home:home' %}">Home</a></span>
                                    <span><a href="{% url 'home:blog' %}">Blog</a></span>
                                    <span>{{ data.h1 }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb area end -->

    <!-- blog area start -->
    <section class="bd-blog-area section-space">
        <div class="container">
            <div class="row gy-30">
                <!-- Blog content -->
                <div class="col-xl-8 col-lg-8">
                    <div class="bd-post-details-wrapper">
                        <div class="bd-post-details-content">

                            <div class="bd-post-details-thumb mb-30">
                                <img src="{{ data.image.url }}" alt="{{ data.h1 }}">
                            </div>

                            <div class="bd-blog-meta flex-wrap mb-2">
                                <span class="me-3"><i class="fa-regular fa-calendar"></i> {{ data.published|date:"F d, Y" }}</span>
                            </div>

                            <h2 class="bd-blog-main-title underline mb-20">{{ data.title }}</h2>

                            <div class="bd-blog-description mb-25">
                                {{ data.content|safe }}
                            </div>

                            {% if data.edits %}
                            <div class="bd-blog-description mb-25">
                                {{ data.edits|safe }}
                            </div>
                            {% endif %}
{% comment %} 
                            {% if data.category.all %}
                            <div class="bd-blog-bottom-tag mb-20">
                                <h6>Categories:</h6>
                                <div class="tagcloud">
                                    {% for cat in data.category.all %}
                                    <a href="#">{{ cat.name }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                            {% endif %}

                            {% if data.tag.all %}
                            <div class="bd-blog-bottom-tag mb-50">
                                <h6>Tags:</h6>
                                <div class="tagcloud">
                                    {% for t in data.tag.all %}
                                    <a href="#">{{ t.name }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                            {% endif %} {% endcomment %}

                        </div>

                        <div class="bd-postbox-navigation mb-50">
                            <a class="bd-postbox-perv-btn" href="{% url 'home:blog' %}">
                                <span class="icon"><i class="fa-sharp fa-solid fa-arrow-left"></i></span>
                                Back to Blogs
                            </a>
                        </div>
                    </div>
                </div>

                <!-- Sidebar -->
                <div class="col-xl-4 col-lg-4">
                    <div class="bd-blog-sidebar sidebar-sticky">

                        <div class="bd-sidebar-widget widget-latest-posts mb-30">
                            <h5 class="bd-widget-title title-bg">Recent Posts</h5>
                            <div class="bd-widget-content">
                                {% for item in data2 %}
                                <div class="bd-recent-post-item">
                                    <div class="bd-recent-post-thumb">
                                        <a href="{% url 'home:blog_detail' item.slug %}">
                                            <img src="{{ item.image.url }}" alt="{{ item.h1 }}">
                                        </a>
                                    </div>
                                    <div class="bd-recent-post-content">
                                        <h6 class="bd-recent-post-title underline">
                                            <a href="{% url 'home:blog_detail' item.slug %}">{{ item.title|truncatechars:40 }}</a>
                                        </h6>
                                        <div class="bd-recent-post-meta">
                                            <span class="icon"><i class="fa-light fa-calendar-days"></i></span>
                                            <span class="date">{{ item.published|date:"d M, Y" }}</span>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- blog area end -->

</main>
{% endblock body %}

home/templates/blog/blogs.html
{% extends 'base.html' %}
{% load static %}

{% block seo %}

{% endblock seo %}

{% block css %}
    
{% endblock css %}
    


{% block body %}
    <main>
    <!-- breadcrumb area start -->
    <section class="bd-breadcrumb-area p-relative fix">
        <div class="bd-breadcrumb-bg" data-background="{% static 'images/bg/breadcrumb-bg.webp' %}"></div>
        <div class="bd-breadcrumb-wrapper p-relative">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-10">
                        <div class="bd-breadcrumb d-flex align-items-center justify-content-center">
                            <div class="bd-breadcrumb-content text-center">
                                <h1 class="bd-breadcrumb-title">Blog</h1>
                                <div class="bd-breadcrumb-list">
                                    <span><a href="{% url 'home:home' %}">Home</a></span>
                                    <span>Blogs</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb area end -->

    <!-- blog area start -->
    <section class="bd-blog-area section-space">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8">
                    <div class="bd-section-title-wrapper section-title-space text-center">
                        <span class="bd-section-subtitle">Latest Blog</span>
                        <h2 class="bd-section-title">Explore Our Latest Insights</h2>
                    </div>
                </div>
            </div>

            <div class="row gy-30">
                {% for post in data %}
                <div class="col-xl-4 col-lg-6 col-md-6">
                    <article class="bd-blog-card wow bdFadeInUp" data-wow-duration="0.3s" data-wow-delay=".{{ forloop.counter }}s">
                        <div class="bd-blog-header">
                            <div class="bd-blog-thumb">
                                <a href="{% url 'home:blog_detail' post.slug %}">
                                    <img src="{{ post.image.url }}" alt="{{ post.h1 }}">
                                </a>
                            </div>
                            {% if post.category.all %}
                            {% for cat in post.category.all %}
                                <span class="bd-badge bg-label-secondary">
                                    <a href="#">{{ cat.category }}</a>
                                </span>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <div class="bd-blog-body">
                            <div class="bd-blog-meta justify-content-between">
                                <div class="bd-blog-author">
                                    <div class="thumb"><img src="{% static 'images/avatar/avatar-01.webp' %}" alt=""></div>
                                    <span><a class="name" href="#">Team Compassionate Care Advisors</a></span>
                                </div>
                                <span class="bd-blog-comments">
                                    <img src="{% static 'images/icon/comments-icon.svg' %}" alt=""> {{ post.published }}
                                </span>
                            </div>
                            <h5 class="title underline">
                                <a href="{% url 'home:blog_detail' post.slug %}">{{ post.h1 }}</a>
                            </h5>
                        </div>
                        <div class="bd-blog-footer">
                            <div class="bd-blog-btn">
                                <a href="{% url 'home:blog_detail' post.slug %}" class="bd-text-btn">Read More
                                    <span class="icon"><i class="fa-light fa-arrow-right"></i></span>
                                </a>
                            </div>
                        </div>
                    </article>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</main>

{% endblock body %}
    


{% block js %}
    
{% endblock js %}
    